## Reading and Writing .CSV and .TSV Files with Pandas
- Reading CSV/TSV Files: How to load data from these files using pandas
- Writing Data to CSV/TSV Files: Save DAtaFrames to these files.

In [20]:
import pandas as pd

In [21]:
df=pd.read_csv('data/example3.txt') #will read comma separated flies (breaks into columns when detects comma)
df

    first line  hi  hello
0  second line NaN    NaN
1   third line NaN    NaN
2  fourth line NaN    NaN
3   fifth line NaN    NaN
4   sixth line NaN    NaN
5  fourth line NaN    NaN
6   fifth line NaN    NaN
7   sixth line NaN    NaN

In [22]:
df=pd.read_csv('data/example3.txt',header=None) #no header(first line won't be bold)
text=df[0].tolist() #convert to list
df
text

['first line',
 'second line',
 'third line',
 'fourth line',
 'fifth line',
 'sixth line',
 'fourth line',
 'fifth line',
 'sixth line']

In [23]:
text

['first line',
 'second line',
 'third line',
 'fourth line',
 'fifth line',
 'sixth line',
 'fourth line',
 'fifth line',
 'sixth line']

In [24]:
url='https://github.com/laxmimerit/All-CSV-ML-DATA-Files-Download/raw/master/jamesbond.csv'
df=pd.read_csv(url,nrows=5) # reads only 5 rows
df

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [26]:
url = 'https://github.com/laxmimerit/All-CSV-ML-DATA-Files-Download/raw/master/spam.tsv'
df=pd.read_csv(url,nrows=10,sep='\t') #here seprator is tab
df

  label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2
5  spam  FreeMsg Hey there darling it's been 3 week's n...     147      8
6   ham  Even my brother is not like to speak with me. ...      77      2
7   ham  As per your request 'Melle Melle (Oru Minnamin...     160      6
8  spam  WINNER!! As a valued network customer you have...     157      6
9  spam  Had your mobile 11 months or more? U R entitle...     154      2

In [27]:
url = 'https://github.com/laxmimerit/All-CSV-ML-DATA-Files-Download/raw/master/spam.tsv'
df=pd.read_csv(url,nrows=10,sep='\t',usecols=['label']) #here seprator is tab
df

  label
0   ham
1   ham
2  spam
3   ham
4   ham
5  spam
6   ham
7   ham
8  spam
9  spam