## Reading and Writing .XLSX Files with Pandas
- Working with Exce Files: How to read and write Excel Files using Pandas.
- Multiple Sheets:Handle Excel Files with multiple sheets.

In [9]:
import pandas as pd
url = 'https://github.com/laxmimerit/All-CSV-ML-DATA-Files-Download/raw/master/Data%20-%20Multiple%20Worksheets.xlsx'
df = pd.read_excel(url)
df

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [10]:
#Check the number of sheets in the file

df=pd.read_excel(url,sheet_name=None)
df
# It has two sheets,if sheet name not provided it takes first sheet by default

{'Data 1':   First Name Last Name           City Gender
 0    Brandon     James          Miami      M
 1       Sean   Hawkins         Denver      M
 2       Judy       Day    Los Angeles      F
 3     Ashley      Ruiz  San Francisco      F
 4  Stephanie     Gomez       Portland      F,
 'Data 2':   First Name Last Name           City Gender
 0     Parker     Power        Raleigh      F
 1    Preston  Prescott   Philadelphia      F
 2    Ronaldo   Donaldo         Bangor      M
 3      Megan   Stiller  San Francisco      M
 4     Bustin    Jieber         Austin      F}

In [11]:
df=pd.read_excel(url)  # sheet name not given so it took first sheet
df

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [ ]:
df=pd.read_excel(url, sheet_name=None) #Here it is necessary to give sheet_name =None as it needs to acces all sheets
df.items()
df1=df['Data 1']
df2=df['Data 2']

In [15]:
df2

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [17]:
df=pd.read_excel(url, sheet_name=None, usecols=['First Name'])
df

{'Data 1':   First Name
 0    Brandon
 1       Sean
 2       Judy
 3     Ashley
 4  Stephanie,
 'Data 2':   First Name
 0     Parker
 1    Preston
 2    Ronaldo
 3      Megan
 4     Bustin}

In [18]:
df1.to_excel('data/df1.xlsx',index=None)

In [21]:
with pd.ExcelWriter('data/multiple_sheet.xlsx')as fp: #we can writ in the excwl file
    df1.to_excel(fp,sheet_name='Data 1')
    df2.to_excel(fp,sheet_name='Data 2')