In [2]:
import json

In [3]:
import pandas as pd
url = 'https://github.com/laxmimerit/All-CSV-ML-DATA-Files-Download/raw/master/Data%20-%20Multiple%20Worksheets.xlsx'
df = pd.read_excel(url, sheet_name = 'Data 1')
df

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [7]:
df.to_json('data/output.json')

In [8]:
df.to_json('data/output.json',orient ='records') #this gives each record separatey in curly braces

In [9]:
df.to_json('data/output1.json',orient ='records',lines='True' ) #to show the records in different lines

In [11]:
#read the json file
d1=json.load(open ('data/output.json'))

In [12]:
d1[2]

{'First Name': 'Judy',
 'Last Name': 'Day',
 'City': 'Los Angeles',
 'Gender': 'F'}

In [14]:
pd.DataFrame(d1)

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [15]:
d1=pd.read_json('data/output.json')
d1

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [ ]:
d2=pd.read_json('data/output1.json',lines=True) #Need to write this coz content in output1 is line wise
d2

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F