## Complete Text Processing

### **A. General Feature Extraction**
- File loading
- Word counts
- Characters count
- Average characters per word
- Stop words count
- Count #HashTags and @Mentions
- If numeric digits are present in tweets
- Upper case word counts

### 1.Data Loader

In [37]:
import pandas as pd
import numpy as np
import re

In [38]:
url = 'https://github.com/laxmimerit/All-CSV-ML-Data-Files-Download/raw/master/twitter4000.csv'
df = pd.read_csv(url)

In [39]:
df.head()

                                              tweets  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tweets     4000 non-null   object
 1   sentiment  4000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 62.6+ KB

In [41]:
df.isnull().sum() #.sum(): In Python, True is treated as 1 and False as 0. When you add .sum(), Pandas adds up all the True values for each column.

tweets       0
sentiment    0
dtype: int64

In [42]:
df['sentiment'].value_counts()

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [43]:
df['sentiment'].value_counts(normalize=True)

sentiment
0    0.5
1    0.5
Name: proportion, dtype: float64

In [44]:
df['sentiment'].value_counts(ascending=True)

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [45]:
df['sentiment'].value_counts(dropna=False)
# The Role of dropna: By default, value_counts() ignores missing data (NaN or Null).
# dropna=True (Default): It only counts the actual values (0s and 1s) and leaves out any empty cells.
# dropna=False: It forces Pandas to include a count for NaN values if they exist.

sentiment
0    2000
1    2000
Name: count, dtype: int64

### 2.Character Count

In [46]:
text='This is character count lesson'
len(text.replace(' ','')) # need to do it as the spaces are not characters

26

In [47]:
pattern=r'\s'
re.sub(pattern,'',text) #Does the same thing as above

'Thisischaractercountlesson'

In [48]:
df['char_count']=df['tweets'].apply(lambda x: len(re.sub(pattern,'',x)))
#.apply(lambda x: ...): This is a "loop" alternative. It tells Pandas to take every row in the tweets column, one by one, and pass it (as variable x) into the function that follows.

### 3.Word Count

In [49]:
x= 'word count example'
print(x.split())
len(x.split())

['word', 'count', 'example']

3

In [50]:
df['word_count']=df['tweets'].apply(lambda x: len(x.split()))

In [51]:
df.sample(5)

,tweets,sentiment,char_count,word_count
1422,@joek949 lol i forgot to post up my cheesy song!,0,39,10
1070,@ABBSound ??????? ????? ??? ???? ??? ??? ?? ??...,0,46,9
27,@tommcfly i have a whole in my shoe too,0,31,9
3828,Operation Nail Paint was a success. Nice shiny...,1,88,18
2834,What a lovely day! I have a feeling today is g...,1,48,14

### 4. Average Word Length

In [52]:
df['avg_word_len']= df['char_count']/df['word_count']

In [53]:
df

,tweets,sentiment,char_count,word_count,avg_word_len
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000
1,back in miami. waiting to unboard ship,0,32,7,4.571429
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538
...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667
3996,Templating works; it all has to be done,1,32,8,4.000000
3997,mommy just brought me starbucks,1,27,5,5.400000
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500

In [54]:
df['avg_word_len']=df['avg_word_len'].apply(lambda x: round(x, 2))

In [55]:
df

,tweets,sentiment,char_count,word_count,avg_word_len
0,is bored and wants to watch a movie any sugge...,0,43,10,4.30
1,back in miami. waiting to unboard ship,0,32,7,4.57
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.50
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.50
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.46
...,...,...,...,...,...
3995,i just graduated,1,14,3,4.67
3996,Templating works; it all has to be done,1,32,8,4.00
3997,mommy just brought me starbucks,1,27,5,5.40
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.62
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.94

### 5. Stop Words Count

In [56]:
from spacy.lang.en.stop_words import STOP_WORDS as stopwords

In [57]:
len(stopwords)

326

In [58]:
x = "This is an example text data. let's use this"
([word for word in x.lower().split() if word in stopwords])

['this', 'is', 'an', 'this']

In [59]:
x = "This is an example text data. let's use this"
len([word for word in x.lower().split() if word in stopwords])

4

In [60]:
df['stop_words_len']=df['tweets'].apply(lambda x:len([word for word in x.lower().split() if word in stopwords]))

In [61]:
df

,tweets,sentiment,char_count,word_count,avg_word_len,stop_words_len
0,is bored and wants to watch a movie any sugge...,0,43,10,4.30,5
1,back in miami. waiting to unboard ship,0,32,7,4.57,3
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.50,1
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.50,3
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.46,13
...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.67,2
3996,Templating works; it all has to be done,1,32,8,4.00,6
3997,mommy just brought me starbucks,1,27,5,5.40,2
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.62,3
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.94,9

### 6. Count #HashTags and @Mentions

In [62]:
x='this is #cool that we can spot @mentions and #hashtags here'

In [63]:
len(re.findall(r'#\w+',x)),len(re.findall(r'@\w+',x))

(2, 1)

In [64]:
df['hashtags_count']=df['tweets'].apply(lambda x:len(re.findall(r'#\w+',x)))
df['mensions_count']=df['tweets'].apply(lambda x:len(re.findall(r'@\w+',x)))

In [65]:
df.sample(5)

,tweets,sentiment,char_count,word_count,avg_word_len,stop_words_len,hashtags_count,mensions_count
1975,I have the biggest effing headache. WTF?,0,34,7,4.86,3,0,0
1869,i have three hours to do my hair. and it STILL...,0,51,14,3.64,10,0,0
428,@ecastillo ta madre... :S,0,22,4,5.50,0,0,1
495,LAUNDRY 2DAY FUCK,0,15,3,5.00,0,0,0
453,@Wimbledon Why isn't Wimbledon radio on?,0,35,6,5.83,1,0,1

In [66]:
df['hashtags_count'].value_counts()

hashtags_count
0    3912
1      73
2      13
3       2
Name: count, dtype: int64

In [67]:
df[df['hashtags_count']>0]

,tweets,sentiment,char_count,word_count,avg_word_len,stop_words_len,hashtags_count,mensions_count
225,Already sent two or three one-forties without ...,0,117,21,5.57,6,1,0
343,"@colderICE will listening from my phone today,...",0,111,25,4.44,12,1,1
427,we want API! http://tinyurl.com/o49vf9 #wolfra...,0,109,12,9.08,2,1,0
468,Stupid bus broke down so will be late to googl...,0,57,14,4.07,6,2,0
475,@Restrictor I can only imagine what it might h...,0,113,23,4.91,11,1,1
...,...,...,...,...,...,...,...,...
3938,#DMCwmnSHOW enjoying the show very much from s...,1,44,8,5.50,5,1,0
3940,At #nfjs Denver! Please indulge me a whole mes...,1,88,16,5.50,7,1,0
3941,#assassinate is also trending because #spymast...,1,65,10,6.50,4,2,0
3944,@darrellferguson If you like Joss Whedon - che...,1,98,21,4.67,8,1,1
3958,Someone has been creative with my #deskmess wh...,1,91,13,7.00,8,1,1

### 7.Numeric Digit Count

In [68]:
x='This is the sample digit data 3 4 5 6 545 6564 '
print(re.findall(r'\d',x))
re.findall(r'\d+',x)

['3', '4', '5', '6', '5', '4', '5', '6', '5', '6', '4']

['3', '4', '5', '6', '545', '6564']

In [69]:
#the above pattern is not right for the texts like below text.
x = 'I want coupon code for product KGP2312AU43 and KGP1243RT. I need 10 pcs.'
re.findall(r'\b\d+\b', x)

['10']

In [70]:
df['numeric_count'] = df['tweets'].apply(lambda x: len(re.findall(r'\b\d+\b', x)))

In [71]:
df[df['numeric_count']>0].sample(5)

,tweets,sentiment,char_count,word_count,avg_word_len,stop_words_len,hashtags_count,mensions_count,numeric_count
3554,Going to the @davejmatthews band concert with ...,1,64,14,4.57,6,0,1,1
2953,@missrogue And yours was $1997 cheaper!,1,34,6,5.67,3,0,1,1
1196,I miss Larry (my spaniel 1994-2006) Nala (my ...,0,57,10,5.70,1,0,0,4
861,@strstruck no &amp; im getting annoyed by not...,0,104,27,3.85,9,0,1,1
2814,@Brian_Mcnugget AARGH. you have 715 tweets. ha...,1,72,13,5.54,4,0,2,1

### 8.UPPER CASE word Count

In [72]:
x='UPPER CASE TEST is going on'

In [73]:
[word for word in x.split() if word.isupper()], len([word for word in x.split() if word.isupper()])

(['UPPER', 'CASE', 'TEST'], 3)

In [79]:
df['upper_counts'] = df['tweets'].apply(lambda x: len([word for word in x.split() if word.isupper()]))

In [80]:
df[df['upper_counts']>0].sample(5)

,tweets,sentiment,char_count,word_count,avg_word_len,stop_words_len,hashtags_count,mensions_count,numeric_count,upper_counts
2173,Good morning! A new rainy &amp; cold day is st...,1,43,10,4.30,2,0,0,0,1
39,Internet still down. Luckily I can watch the g...,0,68,15,4.53,6,0,0,0,2
1377,@JoliOwave Awwww I wish I could b there 2 tak...,0,103,27,3.81,10,0,1,1,2
3914,"@RochelleYap Hmmmmmmm, maybe! After the cip k?...",1,55,11,5.00,5,0,1,0,1
2036,http://twitpic.com/6uftw - I love this cutie,1,39,6,6.50,2,0,0,0,1

In [ ]:
df[df['upper_counts']>3].iloc[0]['tweets'] #.iloc[0] (The Selector): Even if there are 500 tweets that meet your criteria, iloc[0] tells Pandas to grab only the first one in that filtered list.

"@jsong77  NOT DONE IT'S ALMOST 2 AM  this youtbe better start acting normaal"