## Complete Text Processing

### **B. Preprocessing and Cleaning**
- Lower case
- Contraction to Expansion
- Emails removal and counts
- URLs removal and counts
- Removal of RT
- Removal of Special Characters
- Removal of multiple spaces
- Removal of HTML tags
- Removal of accented characters
- Removal of Stop Words
- Conversion into base form of words
- Common Occuring words Removal
- Rare Occuring words Removal
- Word Cloud
- Spelling Correction
- Tokenization
- Lemmatization
- Detecting Entities using NER
- Noun Detection
- N-Gram, Word Count, Lemmatization and POS Tagging
- Using Inbuilt Sentiment Classifier
- Sentence Translation
- Language Detection

### 9. Lower Case Conversion

In [4]:
import pandas as pd
import numpy as np
import re

In [7]:
url = 'https://github.com/laxmimerit/All-CSV-ML-Data-Files-Download/raw/master/twitter4000.csv'
df = pd.read_csv(url)

In [8]:
x = 'IS bored and wants to watch a movie        any suggestions '
x.lower()

re.sub(r'\s+', ' ', x).lower()

'is bored and wants to watch a movie any suggestions '

In [9]:
# we will make the changes on original column itself as we are preprocessing the data.
df['tweets']=df['tweets'].apply(lambda x: re.sub('\s+',' ',x).lower)

In [10]:
df.head()

                                              tweets  sentiment
0  <built-in method lower of str object at 0x0000...          0
1  <built-in method lower of str object at 0x0000...          0
2  <built-in method lower of str object at 0x0000...          0
3  <built-in method lower of str object at 0x0000...          0
4  <built-in method lower of str object at 0x0000...          0

### 10. Contraction to Expansion

In [11]:
import json

contractions = json.load(open('data/contractions.json'))

In [14]:
contractions.get("don't")

'do not'

In [ ]:
# Dictionary lookup: .get(key, default) returns the expanded word if it exists,
# otherwise it keeps the original word to prevent errors.
x = "don't mess with me. I'm done with this stuff."
[contractions.get(word, word) for word in x.split()]

['do not', 'mess', 'with', 'me.', "I'm", 'done', 'with', 'this', 'stuff.']

In [17]:
[contractions.get(word.lower(), word) for word in x.split()]

['do not', 'mess', 'with', 'me.', 'i am', 'done', 'with', 'this', 'stuff.']

In [18]:
" ".join([contractions.get(word.lower(), word) for word in x.split()])

'do not mess with me. i am done with this stuff.'

In [22]:
df['tweets']=df['tweets'].apply(lambda x: " ".join([contractions.get(word.lower(), word) for word in str(x).split()])) #str(x)is imp as without str python is thinking that it's a method and not string.

In [23]:
df

                                                 tweets  sentiment
0     <built-in method lower of str object at 0x0000...          0
1     <built-in method lower of str object at 0x0000...          0
2     <built-in method lower of str object at 0x0000...          0
3     <built-in method lower of str object at 0x0000...          0
4     <built-in method lower of str object at 0x0000...          0
...                                                 ...        ...
3995  <built-in method lower of str object at 0x0000...          1
3996  <built-in method lower of str object at 0x0000...          1
3997  <built-in method lower of str object at 0x0000...          1
3998  <built-in method lower of str object at 0x0000...          1
3999  <built-in method lower of str object at 0x0000...          1

[4000 rows x 2 columns]

In [24]:
df[df['tweets'].str.contains("don't")]

Empty DataFrame
Columns: [tweets, sentiment]
Index: []

### 11. Count and Remove Emails

In [39]:
x = 'contact me at rutujakumbhar@gmail.com and info@rutuja@gmail.com'

pattern = r'\w+@\w+.\w+'
result = re.findall(pattern=pattern, string=x)
print(result)

['rutujakumbhar@gmail.com', 'info@rutuja@gmail']

In [40]:
x = 'contact me at rutujakumbhar@gmail.com and info@rutuja@gmail.co.in'

pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
result = re.findall(pattern=pattern, string=x)
print(result)

['rutujakumbhar@gmail.com', 'rutuja@gmail.co.in']

In [41]:
df['emails'] = df['emails'] =df['tweets'].apply(lambda x: ",".join(re.findall(pattern=pattern, string=x)))

In [42]:
df['emails'].value_counts()

emails
    4000
Name: count, dtype: int64

In [43]:
x = ''
x.count(',')+1 if len(x)>0 else 0

0

In [44]:
df['emails'].value_counts()

emails
    4000
Name: count, dtype: int64

In [45]:
df['emails_count'] = df['emails'].apply(lambda x: x.count(',')+1 if len(x)>0 else 0)

In [46]:
df['emails_count'].value_counts()

emails_count
0    4000
Name: count, dtype: int64

In [47]:
df['tweets'] = df['tweets'].apply(lambda x: re.sub(pattern, '', x))

In [48]:
df.head()

,tweets,sentiment,emails,emails_count
0,<built-in method lower of str object at 0x0000...,0,,0
1,<built-in method lower of str object at 0x0000...,0,,0
2,<built-in method lower of str object at 0x0000...,0,,0
3,<built-in method lower of str object at 0x0000...,0,,0
4,<built-in method lower of str object at 0x0000...,0,,0

### 12. Count and Remove URLs

In [50]:
x='Check this link: https://rutujakumbhar.com and www.rutujakumbhar.com'
pattern=r"http\S+|www\.\S+"
re.findall(pattern,x)

['https://rutujakumbhar.com', 'www.rutujakumbhar.com']

In [54]:
df['urls']=df['tweets'].apply(lambda x: re.findall(pattern,x))

In [55]:
df['urls'].value_counts()

urls
[]    4000
Name: count, dtype: int64